#!/bin/sh
#
changelog_type=1
while test $# -gt 0; do
    case "$1" in
    -*=*)
	optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *)
	optarg=""
	;;
    esac

    case "$1" in
    --spec) # rpm
	changelog_type=1
    ;;
    --debian) # deb
	changelog_type=2
    ;;
    --changes) # open build service
	changelog_type=3
    ;;
	--email=*)
	email=$optarg
	;;
	--version=*)
	version=$optarg
	;;
	--release=*)
	release=$optarg
	;;
	--name=*)
	name=$optarg
	;;
	--state=*)
	state=$optarg
	;;
	--urgency=*)
	urgency=$optarg
	;;
    *)
	if [ -n "$optarg" ] ; then
    	echo "invalid option [$1]" 1>&2
		exit 1
	fi
    ;;
    esac
	shift
done
if [ $# -eq 0 ] ; then
	file=../CHANGES.md
else
	file=$1
fi
if [ $changelog_type -eq 2 ] ; then
	if [ -z "$name" -o -z "$state" -o -z "$urgency" ] ; then
		echo "you have to give --name --state --urgency options" 1>&1
	fi
fi
if [ -z "$version" ] ; then
	if [ -f conf-version ] ; then
		version=$(cat conf-version)
	else
		echo "package version not provided" 1>&2
	fi
fi
if [ -z "$release" ] ; then
	if [ -f conf-release ] ; then
		release=$(cat conf-release)
	else
		echo "package release not provided" 1>&2
	fi
fi
if [ -z "$email" ] ; then
	if [ -f conf-email ] ; then
		email=$(cat conf-email)
	else
		echo "package maintainer not provided" 1>&2
	fi
fi

do_print()
{
	first_char=$(echo "$1" | cut -c1)
	count=$(expr $count + 1)
	if [ "$first_char" = "-" ] ; then
		line=$(echo $1 | cut -c 3-)
		flag_continue=0
	else
		line="$1"
		flag_continue=1
	fi
	case $changelog_type in
		1)
		if [ $flag_continue -eq 0 ] ; then
			printf "%-4s %s\n" "$count." "$line"
		else
			printf "              %s\n" "$line"
		fi
		;;
		2)
		if [ $flag_continue -eq 0 ] ; then
			printf "  * %s\n" "$line"
		else
			printf "             %s\n" "$line"
		fi
		;;
		3)
		if [ $flag_continue -eq 0 ] ; then
			echo "- $line"
		else
			echo "           $line"
		fi
		;;
	esac
}

flag=0
nonewline=0
exec 0<$file
count=0
while read line
do
	if [ $flag -eq 0 ] ; then # first line
		flag=1
		if [ $changelog_type -eq 1 ] ; then
			echo "* `date -u +"%a %b %d %Y %H:%M:%S %z"` $email" "$version"-"$release"%{?dist}
		elif [ $changelog_type -eq 2 ] ; then
			echo "$name ($version-$release) $state; urgency=$urgency"
			echo
		elif [ $changelog_type -eq 3 ] ; then
			printf "%0*d\n" 67 |sed 's}0}-}g' 
			date "+%a, %b %d %H:%M:%S %Z %Y - $email"
			echo
		fi
		do_print "$line"
		continue
	fi
	echo $line | grep -E "[0-9].*version: notqmail.*" >/dev/null
	if [ $? -eq 0 ] ; then
		break
	fi
	do_print "$line"
done

if [ $changelog_type -eq 2 ] ; then
	if [ $nonewline -eq 1 ] ; then
		echo
	fi
	echo
	echo " -- $email  `date -u +'%a, %d %b %Y %H:%M:%S %z'`"
elif [ $changelog_type -eq 3 ] ; then
	if [ $nonewline -eq 1 ] ; then
		echo
	fi
fi
