#!/bin/sh
version=$(cat conf-version)
if [ ! -f  create_archive ] ; then
	echo "create_archive not found in current directory" 1>&2
	exit 1
fi
cd ../..
echo "Preparing notqmail-"$version""
mkdir -p $HOME/stage
/bin/cp -rp notqmail $HOME/stage/notqmail-"$version"
cd $HOME/stage/notqmail-$version
echo "Cleaning notqmail-"$version""
make -s clean >/dev/null 2>&1
# $HOME/stage/
cd ..
echo "Archiving notqmail-"$version".tar.xz in `pwd`"
tar \
	--exclude="notqmail-$version/.git" \
	--exclude="notqmail-$version/opensuse_buildservice"  \
	--exclude="notqmail-$version/autobuilds"  \
	-cf - notqmail-"$version" \
	| xz -c > notqmail-"$version".tar.xz
