#!/bin/sh
#
#
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
if [ ! -f  create_debian ] ; then
	echo "create_debian not found in current directory" 1>&2
	exit 1
fi
make -s
notqmail_version=$(cat conf-version)
/bin/rm -rf   $HOME/stage/notqmail
mkdir -p      $HOME/stage/notqmail-$notqmail_version
cp -rp ..     $HOME/stage/notqmail-$notqmail_version
cp -rp debian $HOME/stage/notqmail-$notqmail_version
cd            $HOME/stage/notqmail-$notqmail_version
dpkg-buildpackage -tc -b -d
/bin/rm -rf $HOME/stage/notqmail-$notqmail_version
ls -lt $HOME/stage
