#!/bin/sh
#
# This script is for creating a RPM package locally
# This script is not used by open build service
# You need to install all dependencies needed
# by notqmail.
# dnf -y install gcc gcc-c++ rpm rpm-build rpmdevtools git
# You may also need to adjust the rpm spec file for macros
# e.g. almalinux_version macro present in open build service
# is missing in the standard distribution where it is almalinux_ver.
# Same issue might happen for rockylinux_version where you may
# want to replace it with rocky_ver
# You can check macros in /usr/lib/rpm/macros.d directory
#
version=$(cat conf-version)
rpmbuild=$HOME/rpmbuild

# generate spec file
make
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

cp notqmail-permissions.easy $rpmbuild/SOURCES
cp notqmail-permissions.secure $rpmbuild/SOURCES
cp system-users-qmail.conf $rpmbuild/SOURCES
cd ..
echo "Preparing notqmail-"$version".xz"
git archive --format=tar.xz --prefix=notqmail-"$version"/ -o $HOME/rpmbuild/SOURCES/notqmail-"$version".tar.xz notqmail-"$version"
rpmbuild -bb open-build-service/notqmail.spec
