task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-2
      image_family: freebsd-11-4

  env:
    matrix:
      - MAKE_FLAGS: -j 2
      - MAKE_FLAGS: "-j 2 NROFF=true"

  pkginstall_script:
    - pkg install -y groff pkgconf check libidn2
  configure_script:
    - echo "clang -O2 -Wall -I/usr/local/include -Wshadow -Werror=implicit-function-declaration -Werror=deprecated-declarations" > conf-cc
    - echo "cc -s -L/usr/local/lib" > conf-ld
  compile_script:
    - make ${MAKE_FLAGS} it man
  test_script:
    - make ${MAKE_FLAGS} test
  install_script:
    - env DESTDIR=/tmp/qmail make package
    - make package
    - pw groupadd -g 200 -n nofiles
    - pw groupadd -g 201 -n qmail
    - pw useradd -u 200 -g nofiles -d /var/qmail/alias -n alias
    - pw useradd -u 201 -g nofiles -d /var/qmail -n qmaild
    - pw useradd -u 202 -g nofiles -d /var/qmail -n qmaill
    - pw useradd -u 203 -g nofiles -d /var/qmail -n qmailp
    - pw useradd -u 204 -g qmail -d /var/qmail -n qmailq
    - pw useradd -u 205 -g qmail -d /var/qmail -n qmailr
    - pw useradd -u 206 -g qmail -d /var/qmail -n qmails
    - ./instchown
    - make check
    - rm -rf /var/qmail
    - make setup check
