dist: xenial
language: c
env:
  matrix:
    - BUILD_NAME="default"
    - BUILD_NAME="utmp" FORCE_UTMP="1" MAKEFLAGS="-o qtmp.h"
    - BUILD_NAME="no_catman" AVOID_NROFF="1"
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
    - pkg-config
    - check
script:
 - echo "${CC} -O2 -Wall -Wshadow" > conf-cc
 - if [ -n "${FORCE_UTMP}" ]; then cp qtmp.h1 qtmp.h; fi
 - if [ -n "${AVOID_NROFF}" ]; then NROFF=true; export NROFF; fi
 - make ${MAKEFLAGS} it man
 - make test
 - env DESTDIR=/tmp/qmail make ${MAKEFLAGS} package
 - sudo make ${MAKEFLAGS} package
 - sudo groupadd -g 200 nofiles
 - sudo groupadd -g 201 qmail
 - sudo useradd -u 200 -g 200 -d /var/qmail/alias alias
 - sudo useradd -u 201 -g 200 -d /var/qmail qmaild
 - sudo useradd -u 202 -g 200 -d /var/qmail qmaill
 - sudo useradd -u 203 -g 200 -d /var/qmail qmailp
 - sudo useradd -u 204 -g 201 -d /var/qmail qmailq
 - sudo useradd -u 205 -g 201 -d /var/qmail qmailr
 - sudo useradd -u 206 -g 201 -d /var/qmail qmails
 - sudo ./instchown
 - sudo make ${MAKEFLAGS} check
 - sudo rm -rf /var/qmail
 - sudo make ${MAKEFLAGS} setup check
