dist: xenial
language: c
env:
  matrix:
    - BUILD_NAME="default" QMAIL_PATH=""
    - BUILD_NAME="TLS" QMAIL_PATH="http://inoa.net/qmail-tls/netqmail-1.06-tls-20190517.patch"
compiler:
 - gcc
 - clang
script:
 - sudo groupadd -g 200 nofiles
 - sudo groupadd -g 201 qmail
 - sudo useradd -u 200 -g 200 -d /var/qmail/alias alias
 - sudo useradd -u 201 -g 200 -d /var/qmail qmaild
 - sudo useradd -u 202 -g 200 -d /var/qmail qmaill
 - sudo useradd -u 203 -g 200 -d /var/qmail qmailp
 - sudo useradd -u 204 -g 201 -d /var/qmail qmailq
 - sudo useradd -u 205 -g 201 -d /var/qmail qmailr
 - sudo useradd -u 206 -g 201 -d /var/qmail qmails
 - if [ -n "${QMAIL_PATH}" ]; then wget -O extra.patch "${QMAIL_PATH}" && patch -p1 -i extra.patch; fi
 - sed "s/^cc /${CC} -Wall /" -i conf-cc
 - make
 - sudo make setup check
