.TH error 3
.SH NAME
error \- syscall error codes
.SH SYNTAX
.B #include <error.h>
.br
.B #include <errno.h>

.SH DESCRIPTION
UNIX syscalls provide detailed error codes in the
.B errno
variable.
The
.B error
library provides portable names for a variety of possible
.B errno
values. Do not use in new code.
.SH "SEE ALSO"
error_str(3),
error_temp(3)
