.TH qlist 1
.SH NAME
qlist \- handle mailing list subscription requests
.SH SYNOPSIS
in
.BR .qmail-\fIlist-request :
.br
.B |qlist
.I user-list@host
.I user-list-request@host
.br
.B .qmail-\fIlist
.B .qmail-\fIlist-request
.B .qtemp-\fIlist
.br
.I owner
[
.I moreinfo
]
.br
(all on one line)
.SH DESCRIPTION
.B qlist
manages a 
.B qmail
mailing list.

When
.B qlist
receives a message,
it looks through the body of the message for commands.
.B WARNING:
.B qlist
looks for a command only at the beginning of a line.
Exception:
.B qlist
also looks at
.B Subject
lines.

.B qlist
supports two commands.
.B SUBSCRIBE
adds a new subscription to the mailing list;
.B UNSUBSCRIBE
removes a subscription.
.B qlist
looks for the subscription address in the
.BR Reply-To ,
.BR From ,
or
.BR Return-Path
fields in the message.

.B qlist
inserts an acknowledgment of each action it took,
along with general help instructions, into the message.
It then forwards the message to the subscription address,
with a copy to
.IR owner .

.BR qlist 's
general help instructions identify
.I user-list@host
as the address of the mailing list,
.I user-list-request@host
as the address of
.B qlist
itself, and
.I owner
as the address
of the mailing list owner.
If
.I moreinfo
is supplied,
it is inserted into the middle of the instructions,
surrounded by blank lines.

.B qlist
maintains its address list in
.BR .qmail-\fIlist ,
so mail to
.I user-list
will be forwarded to each subscription address.
While
.B qlist
is editing
.BR .qmail-\fIlist ,
it locks
.BR .qmail-\fIlist-request .
It uses
.B .qtemp-\fIlist
as a temporary file.

Note that
.B qlist
only manipulates lines beginning with an ampersand;
if you manually add an address without an ampersand,
it cannot be removed by
.BR qlist .

.B qlist
automatically sets the execute bit on
.BR qmail-\fIlist ,
so
.B qmail-local
will ignore any program or file instructions in
.BR qmail-\fIlist .
.SH "SEE ALSO"
dot-qmail(5),
envelopes(5),
qmail-queue(8)
