.TH qmail-qstat 8
.SH NAME
qmail-qstat \- summarize status of mail queue
.SH SYNOPSIS
.B qmail-qstat
.SH DESCRIPTION
.B qmail-qstat
gives a human-readable breakdown
of the number of messages at various spots in the mail queue.

.B qmail-qstat
must be run either as
.B root
or with group id
.BR qmail .
.SH "SEE ALSO"
qmail-qread(8),
qmail-send(8)
