.TH qmail-rcptcheck-realrcptto 8
.SH NAME
qmail-rcptcheck-realrcptto \- realrcptto patch as standalone program
.SH SYNOPSIS
.B qmail-rcptcheck-realrcptto
.SH DESCRIPTION
.B qmail-rcptcheck-realrcptto
is Paul Jarc's realrcptto patch repackaged as a
.BR RCPTCHECK -compatible
program.
It can check envelope recipients during the SMTP protocol conversation,
rejecting any that would eventually bounce due to a missing .qmail file.
.SH ENVIRONMENT
If
.B QMAILRRTDENYALL
is set to
.B 1
in the environment,
then each individual recipient address will be accepted,
but the whole message will be rejected,
to stop attackers from probing for valid addresses.
It's still possible to probe by sending empty, single-recipient messages,
and then sending the real message with all the recipients that weren't rejected.
.SH HISTORY
Originally adapted for rejectutils by Amitai Schleier, based on this code from Paul Jarc:
.PP
.I http://code.dogmap.org/qmail/#realrcptto
.SH "SEE ALSO"
dot-qmail(5),
qmail-rcptcheck(8),
qmail-smtpd(8)
