.TH qmail-upgrade 7
.SH "NAME"
qmail-upgrade \- user-visible differences between qmail and sendmail
.SH "INTRODUCTION"
You will notice some differences
when the system switches from
.B sendmail
to
.BR qmail .
.TP 5
1.
.B qmail-local
sends incoming mail to
.B ~\fIyou\fB/Mailbox
by default,
not
.BR /usr/spool/mail/\fIyou\fB .
Your system administrator has changed your
.B MAIL
environment variable so that your mail reader looks for
.BR ~\fIyou\fB/Mailbox .
.B \fR(\fB/usr/spool/mail
is a massive security problem.)
.TP 5
2.
.B qmail-local
pays no attention to
.BR .forward .
It has a much better mechanism,
.BR .qmail ,
so that you can handle not only forwarding
but even your own mailing lists.
See below for more details.
.TP 5
3.
.B qmail-local
pays no attention to
.BR /etc/aliases .
Your system administrator
can use the
.B .qmail
mechanism instead.
See below.
.TP 5
4.
.B qmail
does not support the
.B \e\fIyou\fB
mechanism
for ignoring aliases.
The
.B .qmail
mechanism is much more flexible;
see below.
.TP 5
5.
.B qmail-inject
has a completely different philosophy from
.B sendmail
on interpreting non-fully-qualified host names.
It uses fixed rules, not DNS.
Some examples at UIC:

.EX
     russet -> russet.math.uic.edu
.br
     newton -> newton.math.uic.edu
.br
     ut.ee  -> ut.ee  (a host in Estonia)
.br
     ut.ee+ -> ut.ee.uic.edu
.br
     uicvm+ -> uicvm.uic.edu
.EE

Here the
.I default domain name
(for hosts without dots)
is
.B math.uic.edu\fP,
and the
.I plus domain name
is
.B uic.edu\fP.
.TP 5
6.
Unlike
.BR sendmail ,
.B qmail-inject
doesn't replace host names with canonical names.
Example:
.B qmail-inject
won't change
.B postmaster@ftp.cs.berkeley.edu
in your header to
.BR postmaster@kohler.cs.berkeley.edu .
.TP 5
7.
.B qmail-local
adds a new field,
.BR Delivered-To ,
before every delivery.
It uses the contents of
.B Delivered-To
to prevent mail forwarding loops.
.TP 5
8.
If you send a message with only
.B Bcc
recipients,
.B qmail-inject
will add
.B Cc: recipient list not shown:;\fR,
rather than
.BR sendmail 's
privacy-invading
.B Apparently-To
header field.
.SH "QMAIL MAILING LISTS"
.B sendmail
deals with aliases, forwarding, and mailing lists
at the very heart of the mail system.

.B qmail
takes a radically different approach.
It gives you the power to set up your own mailing lists without
pestering your system administrator.

Under
.BR qmail ,
you are in charge of all addresses of the form
.B \fIyou\fBBREAK\fIanything\fR.
The delivery of
.B \fIyou\fBBREAK\fIanything
is controlled by
.B ~\fIyou\fB/.qmail-\fIanything\fR,
a file in your home directory.

For example, if you want to set up a
bug-of-the-month-club mailing list,
you can put a list of addresses into
.BR ~\fIyou\fB/.qmail-botmc .
Any mail to
.B \fIyou\fBBREAKbotmc
will be forwarded to all of those addresses.
Mail directly to
.B \fIyou\fB
is controlled by
.BR ~\fIyou\fB/.qmail .
You can even set up a catch-all,
.BR ~\fIyou\fB/.qmail-default ,
to handle unknown
.B \fIyou\fBBREAK
addresses.

Your
.B .qmail
files, like your old
.BR .forward ,
may list files,
forwarding addresses,
or other programs to run.
(But beware that the syntax is a bit different;
see
.B dot-qmail(5)
for more details.)
.B qmail-local
automatically
detects forwarding loops the instant they occur,
even if they happen indirectly through other hosts.

As a helpful special case, if a
.B .qmail
file is empty, it refers to
.BR ~\fIyou\fB/Mailbox .
For example, if you touch
.BR ~\fIyou\fB/.qmail-direct ,
mail for
.B \fIyou\fBBREAKdirect
will act like
.B \e\fIyou\fB
did under
.BR sendmail .

Addresses that don't contain a username are handled by the
.B alias
user.
For example, your system administrator has set up
.B ~alias/.qmail-postmaster
to handle mail for
.BR Postmaster .
(Note to administrators:
.B ~alias
doesn't apply to addresses that start with a user name,
with certain exceptions.)
.SH "SEE ALSO"
addresses(5),
dot-qmail(5),
envelopes(5),
qmail-header(8),
qmail-inject(8)
