.TH qmail-qfilter 1 2020-12-25
.SH NAME
qmail-qfilter \- filter messages before they reach the queue
.SH SYNOPSIS
.B qmail-qfilter
.I filter
[
.I -- filter ...
]
.SH DESCRIPTION
.B qmail-qfilter
lets programs easily inspect and act on messages before they reach the queue.
Each
.I filter
can
accept,
modify before accepting,
reject temporarily, or
reject permanently.
.P
.B qmail-qfilter
runs the given sequence of filters, separated by
.BR \(dq--\(dq .
If any
.I filter
rejects, the message is rejected.
If every
.I filter
accepts,
the message is accepted by executing
.BR qmail-queue .
Exceptions:
.TP 5
.BR 1 .
If
.B QQF_QMAILQUEUE
is set, it specifies an alternate program to be executed. See
.BR "ENVIRONMENT VARIABLES" .
.TP
.BR 2 .
If any filters have written to file descriptor 5
(a temporary file managed by
.BR qmail-qfilter ),
its contents specify an alternate program to be executed.
.P
In any case, accepted messages must be passed to a program that adheres to the
.B qmail-queue
interface.
.P
.B qmail-qfilter
provides a simpler interface.
Each
.I filter
receives the message on its standard input
and the envelope on file descriptor 3.
To pass the message unmodified,
.I filter
may simply exit 0;
otherwise, it must write the modified message to its standard output
and/or the modified envelope to file descriptor 4.
(These are also temporary files managed by
.BR qmail-qfilter .)
.P
A typical
.I filter
reads stdin, perhaps writes stdout, and chooses its exit code carefully.
.SH "EXIT CODES"
Following the
.B qmail-queue
interface,
.I filter
can exit:
.TP 5
.B 0
to accept the message,
.TP
.B 31
to reject the message permanently, or
.TP
.B 82
to reject the message (temporarily or permanently) with a custom error string.
.P
.I filter
can additionally exit:
.TP 5
.B 99
to have
.B qmail-qfilter
exit 0 immediately without running any further filters.
.P
If
.I filter
exits anything other than 0 or 99,
.B qmail-qfilter
exits with
.IR filter's
exit code.
.P
Exception:
If
.B qmail-qfilter
can't create temporary files or execute filters, it exits:
.TP 5
.B 51
Out of memory,
.TP
.B 53
Write error, or
.TP
.B 81
Internal error.
.P
Exception:
If
.B qmail-qfilter
can't read or parse envelope data, it exits
.TP 5
.B 91
Bad envelope data.
.P
(These exit codes, as usual, adhere to the
.B qmail-queue
interface.)
.P
Otherwise,
.B qmail-qfilter
exits with
.BR qmail-queue 's
exit code.
.SH "ENVIRONMENT VARIABLES"
Each
.IR filter 's
environment contains:
.TP 5
.B QMAILPPID
The PID of
.BR qmail-qfilter 's
parent process (e.g.,
.BR qmail-smtpd ).
.TP
.B QMAILUSER
The user part of the envelope sender.
.TP
.B QMAILHOST
The host part of the envelope sender.
.TP
.B QMAILRCPTS
The list of envelope recipients, each followed by a newline.
.TP
.B ENVSIZE
The size of the envelope.
.TP
.B MSGSIZE
The length of the message.
.TP
.B NUMRCPTS
The number of recipients.
.P
For compatibility with previous versions,
.B QMAILNAME
is unset.
.P
Unlike other programs included with qmail,
.B qmail-qfilter
does not run an alternate
.B qmail-queue
if
.B QMAILQUEUE
is set.
This avoids recursive loops with configurations that use
.B QMAILQUEUE
to invoke
.BR qmail-qfilter .
To override
.BR qmail-qfilter 's
invocation of
.BR qmail-queue ,
set
.BR QQF_QMAILQUEUE .
.P
If
.B QQF_DEBUG
is set,
.B qmail-qfilter
will show its work, writing log messages to stderr.
.SH EXAMPLES
To SMTP-reject incoming messages with long
.B Date:
headers,
then add SpamAssassin headers to the rest, create
.BR QMAILHOME/bin/qfilter-block-long-dates :
.P
.EX
    #!/usr/bin/perl
    while (<>) {
      print;
      last if /^\n$/o;
      exit 31 if /^Date: .{80,}/oi;
    }
    while (<>) {
      print;
    }
.EE
.P
Create
.BR QMAILHOME/bin/qfilter-mark-spamminess :
.P
.EX
    #!/bin/sh
    exec spamc
.EE
.P
Finally, create
.B QMAILHOME/bin/qmail-qfilter-smtpd-queue
to run them in sequence:
.P
.EX
    #!/bin/sh
    exec QMAILHOME/bin/qmail-qfilter \\
        QMAILHOME/bin/qfilter-block-long-dates \\
        -- \\
        QMAILHOME/bin/qfilter-mark-spamminess
.EE
.P
Then set
.B QMAILQUEUE
for your
.B qmail-smtpd
service to
.BR QMAILHOME/bin/qmail-qfilter-smtpd-queue .
.SH WARNINGS
If
.I filter
is
.BR "qmail-inject -n",
you may want to run it with
.BR MAILUSER ,
.BR USER ,
and
.B LOGNAME
unset, e.g.:
.P
.EX
    env -u MAILUSER -u USER -u LOGNAME qmail-inject -n
.EE
.P
A message with an excessive number of recipients (more than 64K bytes of
recipient data on Linux) will cause filter programs to fail to execute
and the message to be rejected.
.P
Each
.I filter
gets file descriptor 5 open to the same temporary file.
When writing a program name to it, make sure to write a trailing ASCII NUL byte.
Otherwise, multiple filters could overwrite the value in undesirable ways.
.SH HISTORY
.B qmail-qfilter
was originally written by Bruce Guenter.
.SH "SEE ALSO"
qmail-queue(8)
