#!/bin/sh
#
# Usage: get_function funcation_name filename
# This script helps getting entire code snippet of a function
# from the source code
#
start_line=`grep -n "^$1" $2|cut -d: -f1`
sed -n "$start_line,$"p $2 | while IFS= read -r "line"
do
	echo "$line"
	if [ " $line" = " }" ] ; then
		break
	fi
done
