name: OpenBSD

on:
  push:
    branches: ['**', '!master']
  pull_request_target:
    branches: ['master']
    types:
      - closed

jobs:
  build-openbsd:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    name: >
      ${{ matrix.osversion }}
      ${{ matrix.abi == '64' && ' ' || matrix.abi }}
      ${{ matrix.nroff == 'nroff' && ' ' || matrix.nroff }}
      ${{ matrix.nroff == 'no-roff' && 'no-obsolete' || ' ' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osversion: ["7.4", "7.3", "7.2"]
        abi: [64] # 32
        nroff: ["mandoc", "no-roff"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      uses: vmactions/openbsd-vm@v1
      with:
        release: ${{ matrix.osversion }}
        usesh: true
        prepare: |
          set -e
          pkg_add check
        run: |
          set -e
          echo "cc -m${{ matrix.abi }} -O2 ${{ matrix.nroff == 'no-roff' && '-DDEPRECATED_FUNCTIONS_REMOVED' || ' ' }}" > conf-cc
          echo "cc -m${{ matrix.abi }} -s" > conf-ld
          make -j 2 it man NROFF=${{ matrix.nroff == 'no-roff' && 'true' || matrix.nroff }}
          make -j 2 test
