name: Solaris

on:
  push:
    branches: ['**', '!master']
  pull_request_target:
    branches: ['master']
    types:
      - closed

jobs:
  build-solaris:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    name: >
      ${{ matrix.osversion }}
      ${{ matrix.abi == '64' && ' ' || matrix.abi }}
      ${{ matrix.nroff == 'nroff' && ' ' || matrix.nroff }}
      ${{ matrix.nroff == 'no-roff' && 'no-obsolete' || ' ' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osversion: ["11.4"] # "11.4-gcc"
        abi: [64] # 32
        nroff: ["nroff", "no-roff"]
        libcheck: ["0.15.2"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      uses: vmactions/solaris-vm@v1
      with:
        release: ${{ matrix.osversion }}
        usesh: true
        prepare: |
          set -e
          pkgutil -y -i gcc4core pkgconfig curl
          curl -L -O https://github.com/libcheck/check/releases/download/${{ matrix.libcheck }}/check-${{ matrix.libcheck }}.tar.gz
          gunzip check-${{ matrix.libcheck }}.tar.gz
          tar -xvf check-${{ matrix.libcheck }}.tar
          cd check-${{ matrix.libcheck }}
          env CFLAGS="-m${{ matrix.abi }}" ./configure --prefix=/opt/csw && gmake && gmake install
          sed -e 's|^Libs: |Libs: -Wl,-R${libdir} |' < /opt/csw/lib/pkgconfig/check.pc > /opt/csw/lib/pkgconfig/check.pc.tmp && mv /opt/csw/lib/pkgconfig/check.pc.tmp /opt/csw/lib/pkgconfig/check.pc
        run: |
          set -e
          echo "gcc -m${{ matrix.abi }} -O2 -pipe ${{ matrix.nroff == 'no-roff' && '-DDEPRECATED_FUNCTIONS_REMOVED' || ' ' }}" > conf-cc
          sed -e 's|ar cr |ar Scr |g' make-makelib.sh > make-makelib.sh.tmp && mv make-makelib.sh.tmp make-makelib.sh
          echo "gcc -m${{ matrix.abi }} -s" > conf-ld
          make it man NROFF=${{ matrix.nroff == 'no-roff' && 'true' || matrix.nroff }}
          make test
