name: Ubuntu

on:
  push:
    branches: ['**', '!master']
  pull_request_target:
    branches: ['master']
    types:
      - closed

jobs:
  build-ubuntu:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    name: >
      ${{ matrix.osversion }}
      ${{ matrix.abi == '64' && ' ' || matrix.abi }}
      ${{ matrix.cc == 'gcc' && ' ' || matrix.cc }}
      ${{ matrix.nroff == 'true' && 'no-roff' || ' ' }}
      ${{ matrix.nroff == 'no-roff' && 'no-obsolete' || ' ' }}
      ${{ matrix.utmp == 'autoselect' && ' ' || matrix.utmp }}
    runs-on: ubuntu-${{ matrix.osversion }}
    strategy:
      fail-fast: false
      matrix:
        osversion: ["22.04"] # 20.04's "check" package is too old
        abi: [64]
        warnings: ["-Wall -Wshadow -Werror=deprecated-declarations -Werror=implicit-function-declaration -Werror=parentheses -Werror=dangling-else -Werror=pointer-sign"]
        cc: ["gcc", "clang"]
        nroff: ["nroff", "no-roff"]
        utmp: ["autoselect", "force-old-utmp"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install check
        echo "${{ matrix.cc }} ${{ matrix.nroff == 'no-roff' && '-DDEPRECATED_FUNCTIONS_REMOVED' || ' ' }} -O2 -fPIC ${{ matrix.warnings }} ${{ matrix.cc == 'clang' && '-Werror=incompatible-library-redeclaration' || ' ' }}" > conf-cc
        [ "${{ matrix.utmp }}" = "force-old-utmp" ] && echo "break utmpx detection" >> tryutmpx.c
        make -j 2 it man NROFF=${{ matrix.nroff == 'no-roff' && 'true' || matrix.nroff }}
        make -j 2 test
